---
- name: Setup any hypervisors
  hosts: hypervisors
  tasks:
    - name: Install required packages
      dnf:
        name:
          - bridge-utils
          - libvirt-client
          - python3-libvirt
          - python3-lxml
          - libvirt-daemon-kvm
          - qemu-img
          - qemu-kvm
          - virt-install
          - cloud-utils
          - sshpass
        state: latest

    - name: Check if libvirt image_path exists
      stat:
        path: "{{ image_path }}"
      register: st

    - name: Create libvirt image_path exists
      file:
        path: "{{ image_path }}"
        state: directory
        owner: root
        group: root
        mode: "u=rwx,g=rwx,o=rx"
        seuser: "system_u"
        setype: "virt_var_lib_t"
      register:
        image_create
      when:
        - not st.stat.exists

    - name: Allow libvirt to manage files in image_path
      sefcontext:
        target: "{{ image_path }}(/.*)?"
        seuser: "system_u"
        setype: "virt_var_lib_t"
        state: present
      when:
        - image_create is changed

    - name: Restart libvirtd
      service:
        name: libvirtd
        state: restarted

    - name: List libvirt pools
      virt_pool:
        command: list_pools
      register: pool_list

    - name: Define libvirt default pool
      virt_pool:
        command: define
        name: default
        xml: '{{ lookup("template", "default_storage_xml.j2") }}'
      when: '"default" not in pool_list.list_pools'

    - name: Get libvirt default pool status
      virt_pool:
        command: status
        name: default
      register: default_pool

    # Build a storage pool if it does not exist
    - name: Build libvirt default pool
      virt_pool:
        command: build
        name: default
      when: 'default_pool.status not in "active"' 

    # Ensure that a pool is active (needs to be defined and built first)
    - name: Start libvirt default pool
      virt_pool:
        state: active
        name: default
      when: 'default_pool.status not in "active"' 

    # Ensure that a given pool will be started at boot
    - name: Enable autostart libvirt default pool
      virt_pool:
        autostart: yes
        name: default

    # Check if Qemu has been overriden
    - name: Check if emulator has been overriden
      stat:
        path: "{{ emulator }}.bin"
      register: emulator_bin

    # Setup emulator for nested KVM
    - name: Setup Qemu Emulator with Nested KVM option
      shell: |  
          mv {{ emulator }} {{ emulator }}.bin
          cp {{ playbook_dir }}/files/qemu_override {{ emulator }}
          chmod +x {{ emulator }}
          chcon -t qemu_exec_t {{ emulator }}
      when: emulator_bin.stat.exists == False
