#!/bin/bash

ARGS="$@"

# Check if VM name has a specific string for override (eg. kata)
# if yes
# then add cap-nested-hv=true to machine option

#Machine
MACHINE="pseries-4.1"
NEWMACHINE="pseries-4.1,cap-nested-hv=true"
QEMU="/usr/bin/qemu-system-ppc64.bin"
echo "args: "  ${ARGS}

#Check if qemu arg name have kata
echo ${ARGS} | grep -i kata
if [ $? -eq 0 ]
then
  #Add nested support
  ARGS_1=$(echo ${ARGS} | sed -e 's/'"${MACHINE}"'/'"${NEWMACHINE}"'/g')

  echo "updated args: "  ${ARGS_1}
  exec ${QEMU} ${ARGS_1}
else
  echo "args: " ${ARGS}
  exec ${QEMU} ${ARGS}
fi
